version: "3"
services:
  zookeeper:
    image: "bitnami/zookeeper:3.7"
    restart: always
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - default
    # message broker - kafka
  # reference: https://github.com/bitnami/bitnami-docker-kafka/blob/master/docker-compose.yml
  kafka:
    image: "bitnami/kafka:latest"
    restart: always
    container_name: kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    networks:
      - default
    depends_on:
      - zookeeper
  # message broker - kafka ui
  # reference: https://github.com/cloudhut/kowl/tree/master/docs/local
  kowl:
    image: quay.io/cloudhut/kowl:v1.4.0
    container_name: kowl
    restart: always
    hostname: kowl
    volumes:
      - ./kowl.yml:/etc/kowl/config.yaml
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    ports:
      - "9999:8080"
    networks:
      - default
    depends_on:
      - kafka
networks:
  default:
    name: kafka-network
