version: "3"
services:
  zookeeper:
    image: "bitnami/zookeeper:3.7"
    restart: always
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - default
    # message broker - kafka
  # reference: https://github.com/bitnami/bitnami-docker-kafka/blob/master/docker-compose.yml
  kafka:
    image: "bitnami/kafka:latest"
    restart: always
    container_name: kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: -Xmx512M -Xms512M
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://microservice.kafka.ratchaphon1412.co:29092
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - default
    depends_on:
      - zookeeper
  # message broker - kafka ui
  # reference: https://github.com/cloudhut/kowl/tree/master/docs/local
  kowl:
    image: quay.io/cloudhut/kowl:master
    container_name: kowl
    restart: always
    hostname: kowl
    volumes:
      - ./kowl.yml:/etc/kowl/config.yaml
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    ports:
      - "9999:8080"
    networks:
      - default
    depends_on:
      - kafka
networks:
  default:
    name: kafka-network
